name: teco
channels:
  - defaults
dependencies:
  - ipykernel
  - matplotlib
  - tqdm
  - pandas
  - conda-forge::opencv
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - charset-normalizer==3.3.2
      - filelock==3.9.0
      - filterpy==1.4.5
      - flatbuffers==24.3.7
      - fsspec==2023.4.0
      - gast==0.5.4
      - google-pasta==0.2.0
      - grpcio==1.62.1
      - h5py==3.10.0
      - idna==3.6
      - imageio==2.34.0
      - imutils==0.5.4
      - jinja2==3.1.2
      - joblib==1.3.2
      - keras==3.1.1
      - lazy-loader==0.3
      - libclang==18.1.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - namex==0.0.7
      - networkx==3.2.1
      - opt-einsum==3.3.0
      - optree==0.10.0
      - pandas==2.1.4
      - protobuf==4.25.3
      - requests==2.31.0
      - rich==13.7.1
      - scikit-base==0.7.5
      - scikit-image==0.22.0
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - sktime==0.27.0
      - sympy==1.12
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.1
      - termcolor==2.4.0
      - threadpoolctl==3.4.0
      - tifffile==2024.2.12
      - torch==2.2.1+cpu
      - torchaudio==2.2.1+cpu
      - torchvision==0.17.1+cpu
      - urllib3==2.2.1
      - werkzeug==3.0.1
      - wrapt==1.16.0
