name: teco
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - conda-forge::opencv
  - pip
  - python=3.9
  - jupyterlab
  - notebook
  - pip:
      - appdirs==1.4.4
      - catboost==1.1.1
      - click==8.1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - filelock==3.9.0
      - fonttools==4.50.0
      - fsspec==2023.4.0
      - jinja2==3.1.2
      - kiwisolver==1.4.5
      - markupsafe==2.1.3
      - matplotlib==3.8.3
      - mpmath==1.3.0
      - networkx==3.2.1
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.19.3
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - pandas==2.2.1
      - pillow==10.2.0
      - plotly==5.20.0
      - pyparsing==3.1.2
      - python-graphviz==0.20.3
      - scenedetect==0.6.1
      - scipy==1.12.0
      - sympy==1.12
      - tenacity==8.2.3
      - torch==2.2.1
      - torchaudio==2.2.1
      - torchvision==0.17.1
      - tqdm==4.66.2
      - triton==2.2.0
      - tzdata==2024.1
