name: teco
channels:
  - defaults
dependencies:
  - python=3.9
  - ipykernel
  - opencv
  - pip:
      - appdirs==1.4.4
      - catboost==1.1.1
      - click==8.1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - filelock==3.9.0
      - fonttools==4.50.0
      - fsspec==2023.4.0
      - importlib-resources==6.4.0
      - jinja2==3.1.2
      - kiwisolver==1.4.5
      - markupsafe==2.1.3
      - matplotlib==3.8.3
      - mpmath==1.3.0
      - networkx==3.2.1
      - pandas==1.1.5
      - pillow==10.2.0
      - plotly==5.20.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.20.3
      - pytz==2024.1
      - scenedetect==0.6.1
      - scipy==1.12.0
      - sympy==1.9
      - tenacity==8.2.3
      - torch==2.2.1+cpu
      - torchaudio==2.2.1+cpu
      - torchvision==0.17.1+cpu
      - tqdm==4.42.1
      - typing-extensions==4.8.0
      - zipp==3.18.1
